load("//tools:challenges_list.bzl", "challenges_list")

challenges_list(
    name = "infra_jsonnet",
    visibility = ["//visibility:public"],
    deps = [
        "//infra/ctfd:challenge",
        "//infra/elk:challenge",
        "//infra/flaganizer:challenge",
        "//infra/gaia:challenge",
        "//infra/isodb:challenge",
        "//infra/requestz:challenge",
        "//infra/whoami:challenge",
        "//infra/xssbot:challenge",
    ],
)
